# Generated by Django 4.1.3 on 2022-12-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauna',
            name='quantity',
        ),
    ]
