# Generated by Django 4.1.3 on 2022-12-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0003_remove_sauna_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauna',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sauna',
            name='start_time',
        ),
    ]
